use_frameworks!

platform :ios, '9.0'

target 'MKBaseMQTTModule_Example' do
  pod 'MKBaseMQTTModule', :path => '../'

  target 'MKBaseMQTTModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
